site_name: "Wiki - DataLake"
theme:
  name: material  # El tipo de tema que tenemos asociado
  custom_dir: overrides
  language: es

copyright: Copyright &copy; 2025 - DataOps Team

nav:
  - Inicio: index.md
  - Frentes:
      - Comercial: comercial/index-comercial.md
      - Cloud: cloud/index-cloud.md
      - DataOps:
          - Utilidades:
              - Bash-Github: dataops/utilidades/bash/bash-001.md
          - Componentes:
              - Bigquery:
                  - Calculadora Costos: dataops/bigquery/calculadora-costos.md
              - CloudComposer:
                  - Dag Execution: dataops/cloudComposer/DagExecution/dag-execution.md
                  - Plantillas:
                      - Clasico: dataops/cloudComposer/DagExecution/plantillas/clasicos.md
                      - Custom: dataops/cloudComposer/DagExecution/plantillas/customs.md
              - CloudFunction:
                  - Tipo-Parquet: dataops/cloudFunction/cloudFunctionParquet.md
      - Finanzas: finanzas/index-finanzas.md
      - Supply: supply/index-supply.md
      - SMT: smt/index-smt.md
