name: Deploy Documentation

on:
  push:
    branches:
      - main  # Se activará cuando hagas push a la rama main
      
permissions:
  contents: write   # <--- Importante para permitir push a gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install MkDocs (y Tema Material si lo usas)
        run: |
          pip install mkdocs
          pip install mkdocs-material  # Quita o comenta si no usas este tema
      
      - name: Build Documentation
        run: mkdocs build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site